name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - name: Build
        run: cargo build --verbose --all-features
      - name: Clippy
        run: cargo clippy --verbose --all-features -- -D warnings
      - name: Test
        run: cargo test --verbose --all-features
